learningObjectives:
  - node/npm-install
  - node/package.json
  - node/npm-scripts
  - js/testing/unit
  - js/testing/async
  - js/testing/mocks
  - js/testing/e2e
  - js/modules/es-modules
  - js/modules/commonjs
  - js/linting
  - js/semantics
  - scm/git/setup
  - scm/git/intro
  - scm/git/integration
  - scm/github/setup
  - scm/github/gh-pages
  - scm/github/collaboration
  - scm/github/project-management
  - express/routing
  - express/middleware
  - http
  - auth
  - webops
  - db
